version: '3.2'
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
  run-migrations:
    build: .
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_URL: db:5432
    command: > 
      bash -c "
        flask db init && 
        flask db migrate && 
        flask db upgrade"
    depends_on:
      - db
  api:
    build: .
    command: > 
      bash -c "
            pip install -r requirements.txt && 
            flask run -h 0.0.0.0"
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_URL: db:5432
    ports:
      - "5000:5000"
    depends_on: 
      - db
    volumes:
      - ./:/flask-app